FROM apache/airflow:2.3.3-python3.9

ADD webserver_config.py /opt/airflow/webserver_config.py

USER root

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
         vim \
  && apt-get autoremove -yqq --purge \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

USER airflow

RUN pip install --no-cache-dir \
    pandas \
    psycopg2-binary \
    requests

